package dev.tlang.packages;

import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.regex.Pattern;

/** Strict parser and deterministic writer for tlang.lock format version 1. */
public final class LockfileCodec {
    private static final Pattern SHA256 = Pattern.compile("[0-9a-f]{64}");
    private static final Pattern GIT_SHA = Pattern.compile("[0-9a-f]{40}");

    private LockfileCodec() {}

    public static String write(PackageLock lock) {
        if (lock.formatVersion() != PackageLock.CURRENT_VERSION) {
            throw new PackageException("cannot write unsupported lockfile version " + lock.formatVersion());
        }
        String packageText = writePackages(lock.packages());
        return "# This file is generated by TLang. Do not edit.\n"
            + "lock-version = 1\n"
            + "manifest-sha256 = \"" + lock.manifestSha256() + "\"\n"
            + "graph-sha256 = \"" + PackageHashes.text(packageText) + "\"\n"
            + packageText;
    }

    public static PackageLock parse(String text, String sourceName) {
        if (text == null) throw error(sourceName, 1, "lockfile is empty");
        String[] lines = text.split("\\R", -1);
        Map<String, String> header = new LinkedHashMap<>();
        List<Map<String, String>> rawPackages = new ArrayList<>();
        Map<String, String> current = header;
        for (int index = 0; index < lines.length; index++) {
            String line = stripComment(lines[index]).trim();
            if (line.isEmpty()) continue;
            if (line.equals("[[package]]")) {
                current = new LinkedHashMap<>();
                rawPackages.add(current);
                continue;
            }
            if (line.startsWith("[")) throw error(sourceName, index + 1, "unsupported or malformed lockfile table");
            int equals = line.indexOf('=');
            if (equals < 1) throw error(sourceName, index + 1, "expected 'key = value'");
            String key = line.substring(0, equals).trim();
            String value = line.substring(equals + 1).trim();
            if (current.putIfAbsent(key, value) != null) throw error(sourceName, index + 1, "duplicate field '" + key + "'");
        }
        requireExact(header, Set.of("lock-version", "manifest-sha256", "graph-sha256"), sourceName, "lockfile header");
        int version;
        try { version = Integer.parseInt(header.get("lock-version")); }
        catch (NumberFormatException e) { throw error(sourceName, 1, "invalid lockfile version"); }
        if (version != PackageLock.CURRENT_VERSION) {
            throw error(sourceName, 1, "unsupported lockfile version " + version + " (expected " + PackageLock.CURRENT_VERSION + ")");
        }
        String manifestHash = quoted(header.get("manifest-sha256"), sourceName, 1);
        String graphHash = quoted(header.get("graph-sha256"), sourceName, 1);
        requireHash(manifestHash, "manifest digest", sourceName);
        requireHash(graphHash, "graph digest", sourceName);

        Map<String, PackageRecord> packages = new TreeMap<>();
        for (Map<String, String> fields : rawPackages) {
            String source = quoted(required(fields, "source", sourceName), sourceName, 1);
            Set<String> expected = source.equals("path")
                ? Set.of("name", "source", "path", "content-sha256", "dependencies")
                : Set.of("name", "source", "git", "rev", "commit", "content-sha256", "dependencies");
            if (!source.equals("path") && !source.equals("git")) throw error(sourceName, 1, "invalid package source '" + source + "'");
            requireExact(fields, expected, sourceName, "package record");
            String name = quoted(fields.get("name"), sourceName, 1);
            if (!ManifestCodec.DEPENDENCY_NAME.matcher(name).matches()) throw error(sourceName, 1, "unsafe package name '" + name + "'");
            String contentHash = quoted(fields.get("content-sha256"), sourceName, 1);
            requireHash(contentHash, "content digest for '" + name + "'", sourceName);
            List<String> dependencies = array(fields.get("dependencies"), sourceName);
            if (new HashSet<>(dependencies).size() != dependencies.size()) throw error(sourceName, 1, "duplicate dependency edge for '" + name + "'");
            for (String dependency : dependencies) {
                if (!ManifestCodec.DEPENDENCY_NAME.matcher(dependency).matches()) throw error(sourceName, 1, "unsafe dependency edge '" + dependency + "'");
            }
            PackageRecord record;
            if (source.equals("path")) {
                String path = quoted(fields.get("path"), sourceName, 1);
                try {
                    Path candidate = Path.of(path);
                    if (candidate.isAbsolute() || path.isBlank() || ManifestCodec.looksLikeForeignAbsolutePath(path)) {
                        throw error(sourceName, 1, "unsafe locked path for '" + name + "'");
                    }
                } catch (InvalidPathException e) {
                    throw error(sourceName, 1, "invalid locked path for '" + name + "'");
                }
                record = PackageRecord.path(name, path, contentHash, dependencies);
            } else {
                String git = quoted(fields.get("git"), sourceName, 1);
                String rev = quoted(fields.get("rev"), sourceName, 1);
                String commit = quoted(fields.get("commit"), sourceName, 1);
                ManifestCodec.validateGitUri(git, name, sourceName, 1);
                if (!ManifestCodec.validGitRevision(rev)) throw error(sourceName, 1, "unsafe Git revision for '" + name + "'");
                if (!GIT_SHA.matcher(commit).matches()) throw error(sourceName, 1, "invalid Git commit for '" + name + "'");
                record = PackageRecord.git(name, git, rev, commit, contentHash, dependencies);
            }
            if (packages.putIfAbsent(name, record) != null) throw error(sourceName, 1, "duplicate package record '" + name + "'");
        }
        for (PackageRecord record : packages.values()) {
            for (String dependency : record.dependencies()) {
                if (!packages.containsKey(dependency)) throw error(sourceName, 1, "package '" + record.name() + "' references missing package '" + dependency + "'");
            }
        }
        validateAcyclic(packages, sourceName);
        PackageLock lock = new PackageLock(version, manifestHash, packages);
        String actualGraphHash = PackageHashes.text(writePackages(packages));
        if (!actualGraphHash.equals(graphHash)) throw error(sourceName, 1, "lockfile graph digest mismatch (file may be truncated or modified)");
        return lock;
    }

    private static void validateAcyclic(Map<String, PackageRecord> packages, String source) {
        Map<String, Integer> states = new java.util.HashMap<>();
        java.util.ArrayDeque<String> stack = new java.util.ArrayDeque<>();
        for (String name : packages.keySet()) validateNode(name, packages, states, stack, source);
    }

    private static void validateNode(String name, Map<String, PackageRecord> packages,
                                     Map<String, Integer> states, java.util.ArrayDeque<String> stack,
                                     String source) {
        int state = states.getOrDefault(name, 0);
        if (state == 2) return;
        if (state == 1) {
            List<String> cycle = new ArrayList<>();
            boolean include = false;
            for (String item : stack) {
                if (item.equals(name)) include = true;
                if (include) cycle.add(item);
            }
            cycle.add(name);
            throw error(source, 1, "dependency cycle detected: " + String.join(" -> ", cycle));
        }
        states.put(name, 1);
        stack.addLast(name);
        for (String dependency : packages.get(name).dependencies()) {
            validateNode(dependency, packages, states, stack, source);
        }
        stack.removeLast();
        states.put(name, 2);
    }

    public static void verifyManifest(PackageManifest manifest, PackageLock lock) {
        String actual = PackageHashes.manifest(manifest);
        if (!actual.equals(lock.manifestSha256())) throw new PackageException("manifest and lockfile do not match; run 'tlang install --update'");
        for (DependencySpec dependency : manifest.dependencies().values()) {
            PackageRecord record = lock.packages().get(dependency.name());
            if (record == null) throw new PackageException("lockfile is missing direct dependency '" + dependency.name() + "'");
            boolean locationMatches = record.sourceType() == DependencySpec.SourceType.PATH
                ? record.location().equals(normalizedPath(dependency.location()))
                : record.location().equals(dependency.location());
            if (record.sourceType() != dependency.sourceType() || !locationMatches
                    || (dependency.sourceType() == DependencySpec.SourceType.GIT
                        && !record.requestedRevision().equals(dependency.revision()))) {
                throw new PackageException("locked source for dependency '" + dependency.name() + "' does not match the manifest");
            }
        }
        Set<String> reachable = new HashSet<>();
        java.util.ArrayDeque<String> pending = new java.util.ArrayDeque<>(manifest.dependencies().keySet());
        while (!pending.isEmpty()) {
            String name = pending.removeFirst();
            if (!reachable.add(name)) continue;
            PackageRecord record = lock.packages().get(name);
            if (record == null) throw new PackageException("lockfile is missing package '" + name + "'");
            pending.addAll(record.dependencies());
        }
        if (!reachable.equals(lock.packages().keySet())) {
            Set<String> orphaned = new java.util.TreeSet<>(lock.packages().keySet());
            orphaned.removeAll(reachable);
            throw new PackageException("lockfile contains unreachable package records " + orphaned);
        }
    }

    private static String normalizedPath(String path) {
        return PackageHashes.unix(Path.of(path).normalize());
    }

    private static String writePackages(Map<String, PackageRecord> packages) {
        StringBuilder out = new StringBuilder();
        for (PackageRecord record : new TreeMap<>(packages).values()) {
            out.append("\n[[package]]\n")
                .append("name = \"").append(ManifestCodec.escape(record.name())).append("\"\n")
                .append("source = \"").append(record.sourceType() == DependencySpec.SourceType.PATH ? "path" : "git").append("\"\n");
            if (record.sourceType() == DependencySpec.SourceType.PATH) {
                out.append("path = \"").append(ManifestCodec.escape(record.location())).append("\"\n");
            } else {
                out.append("git = \"").append(ManifestCodec.escape(record.location())).append("\"\n")
                    .append("rev = \"").append(ManifestCodec.escape(record.requestedRevision())).append("\"\n")
                    .append("commit = \"").append(record.commit()).append("\"\n");
            }
            out.append("content-sha256 = \"").append(record.contentSha256()).append("\"\n")
                .append("dependencies = [");
            for (int i = 0; i < record.dependencies().size(); i++) {
                if (i > 0) out.append(", ");
                out.append('"').append(ManifestCodec.escape(record.dependencies().get(i))).append('"');
            }
            out.append("]\n");
        }
        return out.toString();
    }

    private static List<String> array(String encoded, String source) {
        if (encoded == null || !encoded.startsWith("[") || !encoded.endsWith("]")) throw error(source, 1, "dependencies must be an array");
        String body = encoded.substring(1, encoded.length() - 1).trim();
        if (body.isEmpty()) return List.of();
        List<String> values = new ArrayList<>();
        boolean string = false;
        boolean escape = false;
        int start = 0;
        for (int i = 0; i < body.length(); i++) {
            char c = body.charAt(i);
            if (escape) { escape = false; continue; }
            if (string && c == '\\') { escape = true; continue; }
            if (c == '"') string = !string;
            else if (!string && c == ',') { values.add(quoted(body.substring(start, i).trim(), source, 1)); start = i + 1; }
        }
        values.add(quoted(body.substring(start).trim(), source, 1));
        return values;
    }

    private static String quoted(String value, String source, int line) {
        return ManifestCodec.parseString(value, source, line);
    }

    private static String required(Map<String, String> fields, String key, String source) {
        String value = fields.get(key);
        if (value == null) throw error(source, 1, "package record is missing '" + key + "'");
        return value;
    }

    private static void requireExact(Map<String, String> fields, Set<String> expected, String source, String subject) {
        if (!fields.keySet().equals(expected)) {
            Set<String> missing = new HashSet<>(expected); missing.removeAll(fields.keySet());
            Set<String> unknown = new HashSet<>(fields.keySet()); unknown.removeAll(expected);
            if (!missing.isEmpty()) throw error(source, 1, subject + " is missing " + missing);
            throw error(source, 1, subject + " has unsupported fields " + unknown);
        }
    }

    private static void requireHash(String value, String label, String source) {
        if (!SHA256.matcher(value).matches()) throw error(source, 1, "invalid " + label);
    }

    private static String stripComment(String line) {
        boolean string = false;
        boolean escape = false;
        for (int i = 0; i < line.length(); i++) {
            char c = line.charAt(i);
            if (escape) { escape = false; continue; }
            if (string && c == '\\') { escape = true; continue; }
            if (c == '"') string = !string;
            else if (!string && c == '#') return line.substring(0, i);
        }
        return line;
    }

    private static PackageException error(String source, int line, String message) {
        return new PackageException((source == null ? "tlang.lock" : source) + ":" + line + ": " + message);
    }
}
